/**
 * Project-specific message types passed across binding boundaries.
 *
 * The Worker's `Env` type itself is generated by `wrangler types` into
 * `worker-configuration.d.ts` (committed alongside this file), exposed
 * globally as `Env` and via `Cloudflare.Env`. Re-running `wrangler types`
 * after editing `wrangler.jsonc` keeps it in sync.
 */

export interface RecordsJob {
	did: string;
	collection: string;
	rkey: string;
	operation: "create" | "update" | "delete";
	cid: string;
	/**
	 * The Jetstream-supplied (unverified) record bytes. Compared against the
	 * verified PDS copy after fetch as a Jetstream-correctness signal; the
	 * verified copy always wins.
	 */
	jetstreamRecord?: unknown;
}
